export const staff = [
	"",
	"Aaron Storer",
	"Abdullah Saqib",
	"Amit Kumar",
	"Arshed Al Obaidi",
	"Arvinder Toor",
	"Atul Lalotra",
	"Daniel Deeb",
	"Don Jayakody",
	"Ehpoomoo Kunoo",
	"Furqan Tahir",
	"Gavin Rozario",
	"Hamza Khan",
	"Harjeet Singh",
	"Harris Yianoulatos",
	"Hussein Al Shammary",
	"Lisa Wilkins",
	"Majid Butt",
	"Matthew Todorovski",
	"Muhammad Khan",
	"Nobert Francois",
	"Prabhjot Kaur",
	"Rana Hamza Mushtaq",
	"Simarpreet Kaur Walia",
	"Usama Javed",
];
