export default [
	{
		name: "Inactive Alarm. Staff on-site",
		title: "CCURE Alarm Investigation",
		details: "Ref journal. Staff  on-site. Alarm inactive and acknowledged",
		closing: "Usama Javed",
		status: "Closed",
		color: "green",
	},
	{
		name: "Inactive Alarm. Multiple staff on-site",
		title: "CCURE Alarm Investigation",
		details: "Ref journal. Multiple staff members are working on-site. Alarm inactive and acknowledged",
		closing: "Usama Javed",
		status: "Closed",
		color: "green",
	},
	{
		name: "Inactive Alarm. Multiple staff. P1 site",
		title: "CCURE Alarm Investigation",
		details: "Ref journal. Multiple staff are working on-site. P1 site. Alarm inactive and acknowledged",
		closing: "Usama Javed",
		status: "Closed",
		color: "green",
	},
	{
		name: "Active Alarm. Staff on-site",
		title: "CCURE Alarm Investigation",
		details: "Ref journal. Staff  on-site. Alarm active and under observation",
		closing: "Usama Javed",
		status: "Open",
		color: "orange",
	},
	{
		name: "Active Alarm. Multiple staff on-site",
		title: "CCURE Alarm Investigation",
		details: "Ref journal. Multiple staff are working on-site. Alarm active and under observation",
		closing: "Usama Javed",
		status: "Open",
		color: "orange",
	},
	{
		name: "Active Alarm. Multiple staff. P1 site",
		title: "CCURE Alarm Investigation",
		details: "Ref journal. Multiple staff are working on-site. P1 site. Alarm active and under observation",
		closing: "Usama Javed",
		status: "Open",
		color: "orange",
	},
	{
		name: "Active Alarm. Called staff",
		title: "CCURE Alarm Investigation",
		details: "Ref journal. Called staff . Alarm active and under observation",
		closing: "Usama Javed",
		status: "Open",
		color: "red",
	},
	{
		name: "Faulty Alarm",
		title: "Faulty Alarm Log",
		details: "Ref fault list. Alarm is faulty with a NUSR raised already. NFA",
		closing: "Usama Javed",
		status: "Closed",
		color: "green",
	},
	{
		name: "Patrol Dispatch. No-one on site",
		title: "CCURE Alarm Investigation",
		details:
			"Ref journal and maestro. No one appears to be on site. Alarm is not in fault list either. Sending Patrol to investigate further. XXXX Called Wilson NOC () to request a patrol dispatch. Site ID: XXXX",
		closing: "Usama Javed",
		status: "Closed",
		color: "red",
	},
];

export const staff = [
	"",
	"Aaron Storer",
	"Abdullah Saqib",
	"Amit Kumar",
	"Arshed Al Obaidi",
	"Arvinder Toor",
	"Atul Lalotra",
	"Daniel Deeb",
	"Don Jayakody",
	"Ehpoomoo Kunoo",
	"Furqan Tahir",
	"Gavin Rozario",
	"Hamza Khan",
	"Harjeet Singh",
	"Harris Yianoulatos",
	"Hussein Al Shammary",
	"Lisa Wilkins",
	"Majid Butt",
	"Matthew Todorovski",
	"Muhammad Khan",
	"Nobert Francois",
	"Prabhjot Kaur",
	"Rana Hamza Mushtaq",
	"Simarpreet Kaur Walia",
	"Usama Javed",
];
